version: '3.8'

services:
  bank-phishing-detector:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PHISHING_DETECTOR_HOST=0.0.0.0
      - PHISHING_DETECTOR_PORT=8000
      - PHISHING_DETECTOR_LOG_LEVEL=INFO
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - bank-phishing-detector
    restart: unless-stopped
    profiles:
      - with-proxy

volumes:
  logs:
    driver: local
